const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(process.cwd(), '.env.idol'), override: true });

const rootDir = process.cwd();

function boolEnv(value, fallback = false) {
  if (value === undefined || value === null || value === '') return fallback;
  return String(value).toLowerCase() === 'true';
}

function numberEnv(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

const config = {
  rootDir,
  env: process.env.NODE_ENV || 'development',
  port: Number(process.env.PORT || 3000),
  sessionSecret: process.env.SESSION_SECRET || 'dev-session-secret-change-me',
  adminUsername: process.env.ADMIN_USERNAME || 'admin',
  adminPassword: process.env.ADMIN_PASSWORD || 'change-me',
  brandName: process.env.BRAND_NAME || '爱豆加油站',
  autoPublish: boolEnv(process.env.AUTO_PUBLISH, false),
  automation: {
    autoGenerateDailyCandidates: boolEnv(process.env.AUTO_GENERATE_DAILY_CANDIDATES, false),
    autoGenerateWechatDraft: boolEnv(process.env.AUTO_GENERATE_WECHAT_DRAFT, false),
    autoPublishLowRisk: boolEnv(process.env.AUTO_PUBLISH_LOW_RISK, false),
    allowMediumRiskDraft: boolEnv(process.env.ALLOW_MEDIUM_RISK_DRAFT, true),
    allowHighRiskDraft: boolEnv(process.env.ALLOW_HIGH_RISK_DRAFT, false),
    autoPublishMaxPerDay: numberEnv(process.env.AUTO_PUBLISH_MAX_PER_DAY, 1),
    autoDraftMaxPerDay: numberEnv(process.env.AUTO_DRAFT_MAX_PER_DAY, 3)
  },
  search: {
    provider: process.env.SEARCH_PROVIDER || 'mock',
    apiKey: process.env.SEARCH_API_KEY || '',
    region: process.env.SEARCH_REGION || 'KR',
    language: process.env.SEARCH_LANGUAGE || 'ko,en',
    koreanMediaSourceMode: process.env.KOREAN_MEDIA_SOURCE_MODE || 'broad',
    maxSourceUrlsPerRun: numberEnv(process.env.MAX_SOURCE_URLS_PER_RUN, 50),
    maxSourcePackagesPerRun: numberEnv(process.env.MAX_SOURCE_PACKAGES_PER_RUN, 10)
  },
  dbPath: path.resolve(rootDir, process.env.DATABASE_PATH || 'storage/app.sqlite'),
  imageDir: path.resolve(rootDir, 'storage/images'),
  exportDir: path.resolve(rootDir, 'storage/exports'),
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openaiModel: process.env.OPENAI_MODEL || 'gpt-4.1-mini',
};

module.exports = config;
